BlogCW/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from blog.views import (
    PostView,
    CategoryView,
    PostsByCategoryView,
    CreateCategoryView,
    CreatePostView,
    RegisterUser,
    PostDetailView,
    UpdatePostView,
    DeletePostView,
)
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", PostView.as_view(), name="home"),
    path("by_category/<int:pk>/", PostsByCategoryView.as_view(), name="by_category"),
    path("category/<int:pk>/", CategoryView.as_view(), name="category"),
    path("add_category/", CreateCategoryView.as_view(), name="add_category"),
    path("add_post/", CreatePostView.as_view(), name="add_post"),
    path("post_detail/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("post_update/<int:pk>/", UpdatePostView.as_view(), name="post_update"),
    path("post_delete/<int:pk>/", DeletePostView.as_view(), name="post_delete"),
]

urlpatterns += [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("register/", RegisterUser.as_view(), name="register"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy
from django.utils.text import slugify


class Post(models.Model):
    title = models.CharField("Название", max_length=200)
    slug = models.SlugField("", max_length=200)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    category = models.ForeignKey(
        "Category",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name="Категoрия",
    )
    photo = models.ImageField("Фото", upload_to="posts/%Y/%m/%d/", default="No photo")
    updated = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=False)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy("post_detail", kwargs={"pk": str(self.pk)})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ["created"]

    def __str__(self):
        return "Comment {} by {}".format(self.body, self.name)


class Category(models.Model):
    title = models.CharField("Название категории", max_length=150, db_index=True)
    photo = models.ImageField(
        "Фото", upload_to="categories/%Y/%m/%d/", default="No photo"
    )
    about = models.CharField("О категории", max_length=200, null=True, blank=True)

    def post_count(self):
        return Post.objects.filter(category=self).count()

    def get_absolute_url(self):
        return reverse_lazy("category", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["title"]

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from blog.models import Category, Post, Comment


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ["title", "photo", "about"]
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "about": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "rows": 4,
                }
            ),
            "category": forms.Select(attrs={"class": "form-control"}),
        }


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        exclude = ["slug"]
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "content": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "rows": 4,
                }
            ),
            "category": forms.Select(attrs={"class": "form-control"}),
        }
        empty_labels = {"category": "Выберите категорию"}


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(label="Email адрес", help_text="eample@gmail.com")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", "email", "body")

blog/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, \
    DeleteView

from blog.filters import PostFilter
from blog.forms import CategoryForm, PostForm, RegistrationForm, CommentForm
from blog.models import Post, Category


class PostView(ListView):
    template_name = "blog/index.html"
    model = Post

    def get_queryset(self):
        return Post.objects.filter(is_published=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostView, self).get_context_data(**kwargs)
        context["active_category"] = "all"
        context["filter"] = PostFilter(self.request.GET, queryset=self.get_queryset())
        return context


class CreatePostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = "blog/add_post.html"


class UpdatePostView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = "blog/update_post.html"

    def get(self, request, *args, **kwargs):
        post = self.get_object()
        if post.author != request.user:
            raise PermissionDenied
        return super(UpdatePostView, self).post(request, *args, **kwargs)


class DeletePostView(DeleteView):
    model = Post
    success_url = reverse_lazy("home")


class PostDetailView(DetailView):
    model = Post
    template_name = "blog/post_detail.html"
    form_class = CommentForm

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context["comments"] = context.get("post").comments.filter(active=True).order_by("-created")
        context["form"] = self.form_class
        return context

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=kwargs.get("pk"))
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            new_comment.active = True
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
        return self.get(request)


class CategoryView(DetailView):
    model = Category
    template_name = "blog/category.html"
    context_object_name = "category"


class CreateCategoryView(CreateView):
    model = Category
    form_class = CategoryForm
    template_name = "blog/add_category.html"


class PostsByCategoryView(DetailView):
    model = Category
    template_name = "blog/by_category.html"
    context_object_name = "category"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostsByCategoryView, self).get_context_data(**kwargs)
        context["active_category"] = context.get("category").id
        context["post_list"] = Post.objects.filter(
            category=context.get("category"), is_published=True
        )
        return context


class RegisterUser(CreateView):
    """Register user by custom form"""

    form_class = RegistrationForm
    template_name = "registration/register.html"
    success_url = reverse_lazy("home")

blog/templates/blog/add_category.html
{% include 'base.html' %}

{% block content %}
    <div class="m-5">
        <h1>Добавления категории</h1>

        <form action="{% url 'add_category' %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}

            {{ form.non_field.errors }}
            {{ form.as_p }}


            {% comment %}
    {{ form.non_field.errors }}

    <div class="mb-3">

        <label class="form-label" for="{{ form.title.id_for_label }}">Название: </label>
        {{ form.title }}
        <div class="invalid-feedback">
            {{ form.title.errors }}
        </div>

        <label class="form-label" for="{{ form.content.id_for_label }}">Текст: </label>
        {{ form.task }}
        <div class="invalid-feedback">
            {{ form.task.errors }}
        </div>


        <label class="form-label" for="{{ form.content.id_for_label }}">Состояние: </label>
        {{ form.is_published }}
        <div class="invalid-feedback">
            {{ form.is_published.errors }}
        </div>

        <label class="form-label" for="{{ form.content.id_for_label }}">Категория: </label>
        {{ form.category }}
        <div class="invalid-feedback">
            {{ form.category.errors }}
        </div>

    </div>
    {% endcomment %}

            <button class="btn btn-primary btn-block" type="submit">Добавить
                категорию
            </button>


        </form>
    </div>
{% endblock %}

blog/templates/blog/add_post.html
{% include 'base.html' %}

{% block content %}
    <div class="m-5">
        <h1>Добавление новости</h1>

        <form action="{% url 'add_post' %}" enctype="multipart/form-data"
              method="post">
            {% csrf_token %}
            <input type="hidden" name="author" id="id_author" value="{{ user.id }}">
            {{ form.non_field.errors }}

            <div class="mb-3">

                <label class="form-label" for="{{ form.title.id_for_label }}">Название: </label>
                {{ form.title }}
                <div class="invalid-feedback">
                    {{ form.title.errors }}
                </div>

                <label class="form-label" for="{{ form.content.id_for_label }}">Текст: </label>
                {{ form.content }}
                <div class="invalid-feedback">
                    {{ form.task.errors }}
                </div>

                <label class="form-label" for="{{ form.content.id_for_label }}">Категория: </label>
                {{ form.category }}
                <div class="invalid-feedback">
                    {{ form.category.errors }}
                </div>

                <label class="form-label mt-3" for="{{ form.content.id_for_label }}">Фото: </label>
                {{ form.photo }}
                <div class="invalid-feedback">
                    {{ form.photo.errors }}
                </div>

            </div>

            <label class="form-label" for="{{ form.content.id_for_label }}">Опубликовать: </label>
                {{ form.is_published }}
                <br>
                <div class="invalid-feedback">
                    {{ form.is_published.errors }}
                </div>

            <button class="btn btn-primary btn-block" type="submit">Добавить
                новость
            </button>


        </form>
    </div>
{% endblock %}

blog/templates/blog/by_category.html
{% extends "base.html" %}

{% block content %}


    <header class="masthead">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h3 class=" site-heading my-4 mt-3"> Welcome to my
                            awesome Blog </h3>
                        <p class="">We Love Django As much as you do &nbsp
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">
            {% block sidebar %}
                {% include 'blog/sidebar.html' %}
            {% endblock sidebar %}

            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-3 left">
                {% if user.is_authenticated %}
                	<div class="d-flex align-items-center mb-3 {% if not post_list %}
                        justify-content-between
                        {% else %}
                        justify-content-end
                    {% endif %}">
                    {% if not post_list %}
                        Здесь пока пусто, добавьте новость первыми:
                    {% endif %}  <a href="{% url 'add_post' %}"
                                    class="btn btn-primary btn-block w-25"
                                    type="submit">Добавить
                    новость
                </a></div>
                {% endif %}
                {% for post in post_list %}
                    <div class="card mb-4">
                        <img style="max-height: 300px"
                             src="{{ post.photo.url }}" class="card-img-top"
                             alt="...">
                        <div class="card-body">
                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text text-muted h6">{{ post.author }}
                                | {{ post.created }}  </p>

                            <p class="card-text">{{ post.content|safe|slice:":200" }}</p>
                            {#                            <a href="{% url 'post_detail' post.slug %}"#}
                            {#                               class="btn btn-primary">Read More &rarr;</a>#}
                        </div>

                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
        <nav aria-label="Page navigation conatiner"></nav>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}"
                       class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}"
                       class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
        </nav>
        </div>
    {% endif %}
{% endblock %}

blog/templates/blog/category.html
{% extends "base.html" %}

{% block content %}
    <div class="d-flex mt-4 justify-content-center">
        <div style="max-width: 400px" class="card d-flex">
            <img style="max-width: 400px; max-height: 200px" src="{{ category.photo.url }}" class="card-img-top img-thumbnail" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ category.title }}</h5>
                <p class="card-text">{{ category.about|default:"" }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Кол-во новостей в
                    категории: {{ category.post_count }}</li>
            </ul>
            <div class="card-body">
                <a href="{% url 'by_category' category.id %}" class="btn btn-primary">К новостям по категории</a>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}

{% block content %}


    <header class="masthead">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <form class="row justify-content-between align-items-end"
                              id="hideform" method="get">
                            {{ filter.form }}
{#                            {% for field in filter.form %}#}
{#                                <label for="{{ field.id_for_label }}">{{ field.label }} </label>#}
{#                                <div>#}
{#                                {{ field }}#}
{#                                </div>#}
{#                            {% endfor %}#}
                            <div style="justify-content: space-between;"
                                 class="d-flex h-50">
                                <a class="link-warning hide text-center pt-1 mr-2"
                                   id="clearlink" href="{% url "home" %}">Очистить
                                    <i
                                            class="fa-solid fa-filter-circle-xmark bg-transparent"></i></a>
                                <button class="btn btn-primary" type="submit">
                                    Применить
                                </button>
                            </div>
                        </form>
                        <hr>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">
            {% block sidebar %}
                {% include 'blog/sidebar.html' %}
            {% endblock sidebar %}

            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-3 left">
                {% if user.is_authenticated %}
                    <div class="d-flex align-items-center mb-3 {% if not post_list %}
                        justify-content-between
                        {% else %}
                        justify-content-end
                    {% endif %}">
                        {% if not post_list %}
                            Здесь пока пусто, добавьте новость первыми:
                        {% endif %}  <a href="{% url 'add_post' %}"
                                        class="btn btn-primary btn-block w-25"
                                        type="submit">Добавить
                        новость
                    </a></div>
                {% endif %}
                {% for post in filter.qs %}
                    <div class="card mb-4">
                        <img style="max-height: 300px"
                             src="{{ post.photo.url }}" class="card-img-top"
                             alt="...">
                        <div class="card-body">
                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text text-muted h6">{{ post.author }}
                                | {{ post.created }}  </p>

                            <p class="card-text">
                                {{ post.content|safe|slice:":200" }}</p>
                            <a href="{% url 'post_detail' post.id %}"
                               class="btn btn-primary">Read More &rarr;</a>
                        </div>

                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
        <nav aria-label="Page navigation conatiner"></nav>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}"
                       class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}"
                       class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
        </nav>
        </div>
    {% endif %}
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %} {% block content %}
        {% load crispy_forms_tags %}

    <div class="container">
        <div class="row">
            <div class="col-md-8 card mb-4  mt-3 left  top">
                <div class="card-body d-flex flex-column">
                    <img style="max-height: 300px"
                         src="{{ post.photo.url }}" class="card-img-top"
                         alt="...">
                    <h1>{% block title %}
                        {{ post.title }} {% endblock title %}</h1>
                    <p class=" text-muted">{{ post.author }}
                        | {{ post.created }}</p>
                    <p class="card-text ">{{ post.content | safe }}</p>
                    {% if post.author == user %}
                        <div class="d-flex mt-auto justify-content-between">
                            <a href="{% url 'post_update' post.id %}"
                               class="btn btn-primary mt-auto">Изменить</a>
                            <form action="{% url 'post_delete' post.id %}" enctype="multipart/form-data" method="post">
                                {% csrf_token %}
                                <button type="submit"
                                        class="btn btn-danger mt-auto">
                                    Удалить
                                </button>
                            </form>
                        </div>
                    {% endif %}
                </div>
            </div>
            {% block sidebar %}
                {% include 'blog/sidebar.html' %} {% endblock sidebar %}
        

            <div class="col-md-8 card mb-4  mt-3 ">
                <div class="card-body">
                    <!-- comments -->
                    {% with comments.count as total_comments %}
                        <h2>{{ total_comments }} comments</h2>

                        <p>
                    {% endwith %} {% for comment in comments %}
                    </p>

                    <div class="comments" style="padding: 10px;">
                        <p class="font-weight-bold">
                            {{ comment.name }}
                            <span class=" text-muted font-weight-normal">
                                    {{ comment.created }}
                                </span>
                        </p>
                        {{ comment.body | linebreaks }}
                    </div>

                {% endfor %}
                </div>
            </div>
            <div class="col-md-8 card mb-4  mt-3 ">
                <div class="card-body">
                    {% if new_comment %}
                        <div class="alert alert-success" role="alert">
                            Your comment is awaiting moderation
                        </div>
                    {% else %}
                        <h3>Leave a comment</h3>
                        <form method="post" style="margin-top: 1.3em;">
                                                        {{ form | crispy }}
                            {% csrf_token %}
                            <button type="submit"
                                    class="btn btn-primary  btn-lg">Submit
                            </button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

blog/templates/blog/sidebar.html
{% block sidebar %}
    {% load tasks_tags %}


    <!-- Sidebar Widgets Column -->
    <div class="col-md-4 float-right ">
        <div class="card my-4">
            <h5 class="card-header">Категории</h5>
            <ul class="nav nav-pills flex-column">
                {% get_categories as categories %}
                {% for category in categories %}
                    <li class="nav-item">
                        <div class="nav-link ml-2 mr-2 mt-2 {% if active_category and active_category == category.id %}active{% endif %}">
                            <a href="{% url 'by_category' category.id %}"
                               class="{% if active_category and active_category == category.id %}text-white{% endif %}">{{ category.title }}</a>
                            |
                            <a href="{{ category.get_absolute_url }}"
                               class="{% if active_category and active_category == category.id %}text-white{% endif %}"> О категории</a>
                        </div>
                    </li>
                {% endfor %}
                <hr class="m-2 border border-primary border-2 opacity-50">
                <li class="nav-item text-center ml-5 mr-5">
                    <a href="{% url 'home' %}" class="nav-link {% if active_category and active_category == "all" %}active{% endif %}">Все</a></li>
            </ul>
            <div class="card-body">
                <p class="card-text"> Здесь вы можете разделить новости по
                    отдельным категориям</p>
                <a href="{% url 'add_category' %}" class="btn btn-danger">Добавить категорию</a>
            </div>
        </div>
    </div>

{% endblock sidebar %}

blog/templates/blog/update_post.html
{% include 'base.html' %}

{% block content %}
    <div class="m-5">
        <h1>Изменение новости</h1>

        <form action="{% url 'post_update' post.id %}" enctype="multipart/form-data"
              method="post">
            {% csrf_token %}
            <input type="hidden" name="author" id="id_author" value="{{ user.id }}">
            {{ form.non_field.errors }}

            <div class="mb-3">

                <label class="form-label" for="{{ form.title.id_for_label }}">Название: </label>
                {{ form.title }}
                <div class="invalid-feedback">
                    {{ form.title.errors }}
                </div>

                <label class="form-label" for="{{ form.content.id_for_label }}">Текст: </label>
                {{ form.content }}
                <div class="invalid-feedback">
                    {{ form.task.errors }}
                </div>

                <label class="form-label" for="{{ form.content.id_for_label }}">Категория: </label>
                {{ form.category }}
                <div class="invalid-feedback">
                    {{ form.category.errors }}
                </div>

                <label class="form-label mt-3" for="{{ form.content.id_for_label }}">Фото: </label>
                {{ form.photo }}
                <div class="invalid-feedback">
                    {{ form.photo.errors }}
                </div>

            </div>

            <label class="form-label" for="{{ form.content.id_for_label }}">Опубликовать: </label>
                {{ form.is_published }}
                <br>
                <div class="invalid-feedback">
                    {{ form.is_published.errors }}
                </div>

            <button class="btn btn-primary btn-block" type="submit">Изменить
            </button>


        </form>
    </div>
{% endblock %}